version: "3.7"

services:

  traefik:
    image: "traefik:v2.3"
    restart: unless-stopped
    container_name: "traefik"
    ports:
      - "80:80"
      - "8080:8080"
      - "444:444"
      - "446:446"
      - "447:447"
      - "449:449"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      # traefik static configuration
      - ./traefik.yaml:/etc/traefik/traefik.yaml:ro
      # # custom folder with dynamic configuration
      # - ./custom:/etc/traefik/custom:ro
      - ./letsencrypt:/letsencrypt
    networks:
      - web

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`biconou.freeboxos.fr`)"
      - "traefik.http.routers.whoami.entrypoints=websecure-whoami"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.whoami.tls.certresolver=leresolver"
    networks:
      - web
  
networks:
  web:
    name: traefik_web
  