api:
  insecure: true

entryPoints:
  web:
    address: :80

  websecure:
    address: :443

  websecure-dev:
    address: :444
  
  websecure-test:
    address: :446
    
  websecure-prod:
    address: :447
      
  websecure-whoami:
    address: :449

    # accessLog: {}

providers:
  docker:
    exposedByDefault: false

#   file:
#     directory: /etc/traefik/custom/
#     watch: true

certificatesResolvers:
  leresolver:
    acme:
      email: "remi.cocula@gmx.fr"
      storage: "/letsencrypt/acme.json"
      httpChallenge:
        entryPoint: web
